---
- name: check for supported operating system on target
  fail:
    msg: "the operating system of the target machine ({{ inventory_hostname }}) is not currently supported."
  when: ( ansible_distribution|lower != "ubuntu" and ansible_distribution_major_version not in [12, 14, 16] )

- name: include distro specific tasks
  include: "{{ ansible_distribution|lower }}.yml"
